// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// FROM node:14
FROM node:14
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// USER root
USER root
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=run-as-root analyzer=autofix ts=1760254111385]
// RUN apt-get update && apt-get install -y sudo
RUN apt-get update && apt-get install -y sudo
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// COPY . /app
COPY . /app
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// WORKDIR /app
WORKDIR /app
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// CMD ["node", "src/app.js"]
CMD ["node", "src/app.js"]
// PEER-AUTOFIX end [findingId=undefined]
// PEER-AUTOFIX start [findingId=undefined rule=missing-healthcheck analyzer=autofix ts=1760254111386]
// 

// PEER-AUTOFIX end [findingId=undefined]